clojure/config.ini

Moved my blog over to Hexo and Github pages, so updating the feed url

Updated jr0cket blog link

---

clojure/config.ini

I'm rebooting my blog with a new feed.

Changed blog for Steve Miner

---

clojure/config.ini

Added Jozef Wagner's blog

---

clojure/config.ini

It is feed of Medium publication. The contents are the story about our office boy who starts to learn coding. I teach him Clojure as his first programming language. I assume that Clojure is very easy to understand by first timer because its core language is small; everything is an expression in Lisp dialect; and functional programming (in my opinion) will be easy to grok by newbie who never did programming before.

Adding GaluhProject feed

---

clojure/config.ini

Changing the name of my Medium publication to my office name and adding my Clojure experimentation blog to my real name (personal Clojure blog).

Adding my personal Clojure blog feed.

---

clojure/config.ini

Adding jamiei.com

---

clojure/config.ini

config.ini: add camdez.com

---

clojure/config.ini

Added LambdaCat to config.ini

---

clojure/config.ini

Hi,
thanks a lot for maintaining planet.clojure.in.
I would like to add my blog (the posts tagged with "Clojure") to planet.clojure.in.
I hope that the pull request and the way for adding my blog are OK.
Best regards,
Ruediger

Add posts tagged with 'clojure' from ruedigergad.com.

---

clojure/config.ini

Hi,
I'm changing my site's url and moving all the posts about Clojure and ClojureScript to there.
Thanks.

Changing My Clojure's Blog URL

---

clojure/config.ini

I added the Clojure feed of my blog to the config.ini file. Thanks for maintaining this.

Added Sprung Canary Clojure feed to config.ini

---

clojure/config.ini

Updated Martin Skou name and link.

---

clojure/config.ini

I hope I have done everything correctly!

Add the Scalac Blog to the Clojure feed

---

clojure/config.ini

Update feed url to use SSL

---

clojure/config.ini

add simonb.com

---

clojure/config.ini

Now that my website is based on Jekyll, I can write more posts easily _and_ have an XML feed. The link in the patch will only have the English posts. Thank you in advance.

Add Functional Bytes blog

---

clojure/config.ini

It replaces  Scalac one, brand new brand :smile: 
Thank you!

LambdaX blog

---

clojure/config.ini

I've been following planet.clojure for a few years now. Thanks so much for this service!
I'm trying to blog once a week about clojure related topics and I'd like to add my blog to the list, please let me know if you need anything else. 
Dave

add upgradingdave.com blog

---

clojure/config.ini

Remove John Mastro's feed

---

clojure/config.ini

This is the feed for just posts with the Clojure tag

Add Ladders Engineering Blog

---

clojure/config.ini

I am using a new blog platform, so I have a new url for my specific Clojure feed

Update jr0cket feed url

---

clojure/config.ini

Hi Planet Clojure team!
Could you please add my blog to your site?
Thank you and best regards,
Olivier Barbeau

add 'The world in an atom' blog

---

clojure/config.ini

Atom feed should now be fixed.
https://twitter.com/JuhoTeperi/status/701836657243377664
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fderaen.github.io%2Fatom.xml

Enable Deraen's blog

---

clojure/config.ini

Hi,
Here is a link to my blog with Clojure related feeds. Let me know if I need to provide anything else.
Thanks!
Sanel

Add acidwords.com blog

---

clojure/config.ini

Added Metosin blog to config.ini

---

clojure/config.ini

We might write about business cases etc. not related to Clojure so a
filter is probably a good idea.

Add filter to Metosin blog

---

clojure/config.ini

I'm working on a series of Clojure articles about Serverless on AWS.

Add @jamesleonis on Medium

---

clojure/config.ini

Main site at https://therepl.net

Add The REPL

---

clojure/config.ini

Add farenda.com

---

clojure/config.ini

This is the feed for the Clojure/GSoC blog.

Add Clojure/GSoC

---

clojure/config.ini

I'd love to add the Clojure posts from our engineering site to Planet Clojure.
Thanks!

Add CollBox Engineering feed

---

clojure/config.ini

It's my blog, I write about Clojure every now and then. https://quanttype.net/topic/clojure.html

Add quanttype

---

clojure/config.ini

Added https://www.opensourcery.co.za/clojure.xml (Clojure-specific) feed

Add Open Sourcery

---

clojure/config.ini

I've restarted by blog and have a new feed setting. Can you update your site when you have a moment.
Thanks very much
- Brad

update feed setting for Brad Lucas

---

clojure/config.ini

New Mark Bastian blog

---

clojure/config.ini

Replaced old non-existent URL with new RSS (clojure tag).

updated uSwitch labs rss

---

clojure/config.ini

Do you know offhand whether the filter applies to category tags in the feed? Thanks in advance.

Add my blog with an appropriate filter

---

clojure/config.ini

Add my blog 'Curious (Clojure) Programmer'

---

clojure/config.ini

Fixed my blog feed and added filter

Fixed Paulo Suzart feed url

---

clojure/config.ini

Just an update to the URL for the RSS feed from my site.

Update feed URL for Ray Miller.

---

clojure/config.ini

I am removing my inactive blog from the feed.

Remove Andrew Meredith

---

clojure/config.ini

Add Clojure posts in tirkarthi.github.io to the list

Add tirkarthi.github.io

---

clojure/config.ini

Hi! This is my Clojure blog which features "(just juxt!)". We spoke on Slack yesterday. Thanks!

added my Clojure blog

---

clojure/config.ini

remove site now serving spam

---

clojure/config.ini

Hi,
I updated my blog config because I have moved my blog from blogspot to github pages. Please merge if looks ok.

Updated with new site and blog rss

---

clojure/config.ini

Hi! If you go check the feed within the next couple of days it might be empty, but my first Clojure post is basically ready and I'm just finishing it to publish it during this week.

Add rDisorder

---

clojure/config.ini

please consider adding. thanks!

add Henry Widd blog

---

clojure/config.ini

Please approve the  pull request

Added my blog

---

clojure/config.ini

Hi,
Thanks for updating my blog's url.

updating my blog's url

---

clojure/config.ini

Hi, thanks a lot for providing planet.clojure. After years I've created a new blog about Clojure topics. I would be very thankful, if you add my blog to planet.clojure
Best regards and a great day,
Max

Added blog https://maxweber.github.io

---

clojure/config.ini

Add Clojure posts in whynotsoftware.github.io to the list

Add whynotsoftware.github.io

---

clojure/config.ini

Hi,
PR to get my blog feed added please. The RSS feed is Clojure only.
I don't have a twitter account.

Clojure blog feed for Nick Jones added.

---

clojure/config.ini

Hi @alexott,
Thanks for planet clojure. I've been a fond reader over the years. I'm starting up my own blog in which most of the posts will have an emphasis on the intersection of kafka, clojure, and testing.
Cheers,
Andy

Add grumpy hacker blog

---

clojure/config.ini

Three more Clojure blogs with recent activity.

Add Alexander Oloo, Erik Assum, Practicalli

---

clojure/config.ini

This is a brand new feed for the site.

Add Clojurists Together blog feed

---

clojure/config.ini

Update URL for camdez.com

---

clojure/config.ini

https://news.ycombinator.com/item?id=24705731 
Suggestion from @alexott  -- great project team!

Add stopa.io to planet clojure

---

clojure/config.ini

Hi, I would like to add my blog to the planet.

Added my blog post - ieugen.ro

---

clojure/config.ini

Hi, as we talked on Twitter here's the link to my feed

add Thomas Sojka's Blog

---

clojure/config.ini

Let me know if there are any issues with the feed, and I will fix quickly. Thanks!

Add John Oerter's blog

---

clojure/config.ini

I recently add topic-specific feeds to my blog, so this should be the way to subscribe to specifically posts about Clojure now. Thank you so much for adding my blog to Planet Clojure!

Update Kira McLean's blog feed

---

clojure/config.ini

Fix Reblog

---

clojure/config.ini

added Sharas Mazylis clojure feed

---

clojure/config.ini

I am learning to code. I am learning Clojure, as a part of my preparation. I plan to post a few posts related to Clojure on my [blog](https://otee.dev/)

Add Otee's blog

---

clojure/config.ini

Hi, Planet Clojure!
I'm writing about Clojure and would be glad to be added here. 
Thanks.

Added Volodymyr Kozieiev's blog

---

clojure/config.ini

Please add Clojure Crazy. Thanks.

Add Clojure Crazy

---

clojure/config.ini

I moved the blog from Wordpress to Cryogen.
https://curiousprogrammer.net/feed.xml

Update curiousprogrammer.net feed URL.

---

clojure/config.ini

I'm migrating domains from Lispcast.com and PurelyFunctional.tv to EricNormand.me. Just updating and combining.

Update Eric Normand's sites

---

clojure/config.ini

Update danielcompton.net RSS feed

---

clojure/config.ini

It appeared that my twitter nickname is incorrect and points to another person.

Updated twitter account for Volodymyr Kozieiev

---

clojure/config.ini

https://avelino.run/tags/clojure/

add avelino.run clojure tag feed

---

clojure/config.ini

add Miro Bezjak blog

---

clojure/config.ini

Hi! Added my new blog. I'm planning to blog about Clojure and other stuff every now and then.
Feed is for planet clojure. I don't have Twitter account (anymore).

Added Mikko Koski's blog

---

clojure/config.ini

Thanks for including my blog. This is a Clojure-tag specific feed.

update Nate Jones' url to Clojure-specific feed

---

clojure/config.ini

Add Clojure blog to feed. This is a website I've made to document my year of open source work in the Clojure community. Thank you for maintaining this great list of Clojure blogs!

Update config.ini with codewithkira.com
