ghoseb/planet.clojure

clojure/config.ini

We did a site redesign and some of our URLs changed. Just updating the config so that the URL is correct and no longer 404s.

Updated The BHW Group URL to match new tag url structure.

---

clojure/config.ini

I'm removing my old wordpress blog and merged the content into the main
site for zeekat.nl. New articles about clojure will be posted there.

Remove old blog, point feed to new location

---

clojure/config.ini

We have merged our blog into our website, so this change reflects that.

Update JUXT blog

---

clojure/config.ini

Feed fetching was failing on handshake.
I verified that this fetch works locally via `python spider.py ./clojure/config.ini`

Remove TLS for christopherdbui.com

---

clojure/config.ini

Hi! I wanted to add [my company's engineering blog](https://tech.kontor.com/) to Planet Clojure. Hopefully the filters work, as Medium doesn't have a lot of options for RSS filters and we have various non-Clojure content that pops up there from time to time.

Adding Kontor tech blog

---

clojure/config.ini

I've moved to a new site. This is the better feed.

Change Clojure Gazette Feed link

---

clojure/config.ini

This feed only provides posts tagged with `clojure` so it doesn't require a filter.

Add bevuta IT GmbH blog

---

clojure/config.ini

The first feed is for the blog, which is 100% Clojure related content.
The second feed contains all the free screencasts.

Add Lambda Island blog + free episodes

---

clojure/config.ini

PrecursorApp feed (https://precursorapp.com/blog.rss) returns current time `pubDate` for their latest blog entry, making it re-appear in the feed repeatedly.
I've asked them to fix it [1], but in the meantime to stop this annoyance their feed could be removed.
[1] https://twitter.com/ernestas/status/798563820209774592

Remove broken PrecursorApp feed

---

clojure/config.ini

We post about Clojure as well as other topics. All Clojure related posts are in the category called "clojure". so I limited the feed url to that.

added bigsolutions.io blog

---

clojure/config.ini

Clojure Gazette now redirects to PurelyFunctional.tv, but the feed was not set up. Now only stuff with the Clojure tag will go through.
Rock on!
Eric

Moved my site to PurelyFunctional.tv domain

---

clojure/config.ini

Klarna is a Stockholm-based company that uses Clojure in production and has sponsored a ClojureBridge workshop. We have occasional posts on Clojure on our engineering blog.
This PR adds posts tagged as Clojure from the blog.

Add Clojure tag of Klarna Engineering blog

---

clojure/config.ini

I used the `filter` option on the main feed that everyone else was using, but if you need a more specific feed, I can switch it to http://modulolotus.net/clojure.xml.

Added modulolotus.net

---

clojure/config.ini

https://www.therepl.net. The newsletter is syndicated via a Mailchimp RSS feed, but the podcast isn't part of that feed.

Add The REPL podcast

---

clojure/config.ini

Changed Kari Marttila's blog from Medium to Github Pages.
Rationale: Github Pages provides a lot better visualization e.g. for code blocks.
I created a clojure category feed as requested.

Changed Kari Marttila's blog from Medium to Github Pages

---

clojure/config.ini

Hello, Planet Clojure!
This PR adds the Crux Blog with a Clojure filter. We do have a hard category for Clojure posts as well, but it seems Venus can't parse RSS categories and filter on them explicitly? Let me know if you would prefer that we create an entirely separate, Clojure-only feed based on our `clojure` category in the blog.
Thanks!
-steven

Add Crux Blog with Clojure filter

---

clojure/config.ini

- Add dop to regex (stands for Data-Oriented programming)
- Remove read.klipse.tech (the site not longer exists)

Update klipse configuration

---

clojure/config.ini

I've added a separate Clojure feed based on post metadata, which should better filter out non-Clojure posts.

Switch to Metosin clojure.xml feed

---

clojure/config.ini

I've figured out why my feeds for tags contained the same information as the base feed and fixed that. So, to avoid false positives that happen, when I write posts about Fennel, in which I often reference Clojure, I've changed the feed link to two links for each feed.

Use clojure and clojurescripts specific feeds

---

clojure/config.ini

Hi there,
I removed the link to my (no longer existing) Twitter Account for my personal blog, and added our technical company blog which will will also contain Clojure postings.
If you'd like to have those two changes separately, of if you feel uneasey about adding the blog on our company website (will stay free from advertising and marketing, purely technial), then I'd be able to separate the changes.

Removed personal Twitter account, added company blog

---

clojure/config.ini

Hey, I added a feed with all our clojure blogs in one place.
That should be slightly better than having a 404 page 😅

fix: add clojureplanet specific feed

---

clojure/config.ini

Blog migrated to Material for MkDocs and has a new URL for the RSS feed.

config: updated feed url for Practical.li blog

---

clojure/config.ini

Practicalli home page and blog has merged and unfortunately it wasnt possible to set the location of the feed to the same location as the updated blog.
Sorry for the inconvenience.

config: practicalli blog feed moved again (sorry)
